name: Print Collaborator and Project Name

on:
  push:
    branches:
      - branch1

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print collaborator (actor) and project name
        run: |
          echo "Collaborator (Actor): ${{ github.actor }}"
          echo "Project name: ${{ github.repository }}"
